---
title: "post_prediction"
author: "Zach Tefertiller"
date: "2025-04-09"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(bayesplot)
library(ggplot2)
library(rstan)
library(pryr)
library(loo)
```


```{r simulate STL}
# this is to take our estimated latent parameters from the stl model per participant and see if it can generate the outcomes observed in the data that we estimated our parameters from
stl_post_pred <- function(participant_data) {
  
  # get static variables
  participant_id <- participant_data$participant_id
  vwin <- participant_data$vwin
  vloss <- participant_data$vloss
  omegaone <- participant_data$omegaone
  beta <- participant_data$beta
  
  # print(vwin)
  
  logit_sim <- function(omega)
    pump_probability <- 1/(1 + exp(beta*(opportunity-omega)))
  
  for (i in participant_data$trial_number) {
    if (popped == 1) {
      nmax <- participant_data$optimal_inflations[i]
      omega <- (omegalast * ( 1 - vloss * ( 1 - (npump/nmax))))
      df$omega[i] <- omega
      npump <- (logit_sim(omega))
      df$inflations[i] <- npump 
    }
    else {
      nmax <- participant_data$optimal_inflations[i]
      omega <- (omegalast * ( 1 + (vwin * (npump/nmax))))
      df$omega[i] <- omega
      npump <- (logit_sim(omega))
      df$inflations[i] <- npump
    }
  }
}
 

```


```{r}

# function to loop over all participants
main <- function(df) {
  for (participant in df$participant_id) {
    participant_data <- df[df$participant_id == participant,]
    stl_post_pred(participant_data)
  }
}
```